theme: jekyll-theme-cayman
title: Design & Development â€¢ Newmark J School
description: A class in product design, development, and prototyping. By John Keefe at the Newmark Graduate School of Journalism at the City University of New York.
